"""add link field to experience table

Revision ID: 19978dd8c078
Revises: 784122ae1c8a
Create Date: 2025-02-03 18:18:41.051475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19978dd8c078'
down_revision: Union[str, None] = '784122ae1c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'link')
    # ### end Alembic commands ###
