"""Create about_paragraphs table

Revision ID: 784122ae1c8a
Revises: 3b72f94d5062
Create Date: 2025-02-02 22:59:44.788939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784122ae1c8a'
down_revision: Union[str, None] = '3b72f94d5062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'about')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('about', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
